### ISSUE TITLE
no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0. And because matrix >=0.13.0 depends on ffi ^2.0.0, open_file ^3.2.1 is incompatible with matrix >=0.13.0.

### ISSUE THREAD

**Issue by ialyzaafan** [crazecoder/open_file#225]

**Comment by nikohpng** [comment]
same issue

**Comment by briosheje** [comment]
This happens with every package that uses a version of ffi greater than 2.0.0

**Comment by acquytrenthienduong** [comment]
same issue. anyone have solution

**Comment by acquytrenthienduong** [comment]
Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
And because file_picker >=5.0.0 depends on ffi ^2.0.1, open_file ^3.2.1 is incompatible with file_picker >=5.0.0.
So, because ccs depends on both file_picker ^5.2.3 and open_file ^3.2.1, version solving failed.
pub get failed (1; So, because ccs depends on both file_picker ^5.2.3 and open_file ^3.2.1, version solving failed.)

**Comment by bsolca** [comment]
Same here:

Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
And because every version of amos_mobile_widgets from path depends on file_picker ^5.2.2 which depends on ffi ^2.0.1, open_file ^3.2.1 is incompatible with amos_mobile_widgets from path.
So, because amos_mobile_etlb depends on both amos_mobile_widgets from path and open_file ^3.2.1, version solving failed.

**Comment by RobertHeim** [comment]
The package seems abandoned. Use the fork `open_file_plus`

* pub.dev: https://pub.dev/packages/open_file_plus
* github: https://github.com/joutvhu/open_file_plus
