### ISSUE TITLE
I used the open_file safe package in flutter, but after the file is downloaded, it does not open when clicked, so the file does not go to the download directory.

### ISSUE THREAD

**Issue by serkanagca34** [crazecoder/open_file#233]
I used the open_file safe package in flutter, but after the file is downloaded, it does not open when clicked, so the file does not go to the download directory. I used the open_file package, but since google play console gave 'REQUEST_INSTALL_PACKAGES' error, I replaced it with open_file safe. I tried many packages ( open_file safe, open_file plus etc. ) none of them worked. how can i solve this problem?
<img width="1728" alt="Screenshot 2022-11-14 at 11 41 00" src="https://user-images.githubusercontent.com/62822922/201625462-c5d521c3-55fa-49b6-80c3-787bdc71186e.png">
<img width="1728" alt="Screenshot 2022-11-14 at 11 44 17" src="https://user-images.githubusercontent.com/62822922/201625484-cdec5497-a40f-4466-8147-c3e68221a5f5.png">
![Screenshot_1668415763](https://user-images.githubusercontent.com/62822922/201625497-5299a5dc-2247-4cae-ae77-f96685613c71.png)

**Comment by shashikiran918** [comment]
I used the open_file safe package in flutter, for me also same issue it is not downloading

**Comment by technolion** [comment]
This is a problem on Android only. It happens because the native part of the plugin gets a permission error. When debugging I found the following error in the `resultMap` [here](https://github.com/crazecoder/open_file/blob/master/lib/src/platform/open_file.dart#L58):

`Permission denied: android.Manifest.permission.MANAGE_EXTERNAL_STORAGE`

I can't place this error, because the cached data is stored in the internal storage of the Android storage system. In my case:
`/data/user/0/com.skalio.spaces.client/files/cache/ptj5y5sg6qfynm9i/DJI_0298.jpg`

So, why does the plugin complain about external storage?

**Comment by crazecoder** [comment]
Try 3.3.0
