### ISSUE TITLE
not working in android 33

### ISSUE THREAD

**Issue by aju-annaseem** [crazecoder/open_file#261]
Nothing happen in android 33

**Comment by mobinshaik999** [comment]
Same here 
No Error , No Log

**Comment by buchori28** [comment]
I am too

**Comment by jivaraj123** [comment]
Same error

**Comment by feykro** [comment]
Hello @mobinshaik999 , @buchori28 , @jivaraj123 

Your issue lies with the fact you do not have permission to access user storage.
I have documented this issue in more details here: https://github.com/crazecoder/open_file/issues/265
You will also find a work-around for apps that work as long as you do not want to publish your app on the official store.

Cheers.

**Comment by aju-annaseem** [comment]
i want to upload my app to the Play Store. what do I do?
