### ISSUE TITLE
Didn't work on android 5 api 22

### ISSUE THREAD

**Issue by hosein-nadali** [crazecoder/open_file#85]
Hey guys.
I can't open file on android 5
There is no error just can't open file.

**Comment by ivan07josiel** [comment]
Same problem here, additionally I was able to capture this message in the emulator's Logcat:

`2133-2395/system_process I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.example.HIDDEN_APP_NAME.fileProvider/external-path/Download/FILE_NAME.pdf typ=application/pdf flg=0x20000001} from uid 10051 on display 0`

**Comment by Abapel** [comment]
I also could not open files that are stored in getApplicationDocumentsDirectory on Android 5, but when I moved them to getExternalStorageDirectory, they began to open normally.

**Comment by AliEasy** [comment]
> I also could not open files that are stored in `getApplicationDocumentsDirectory` on Android 5, but when I moved them to `getExternalStorageDirectory`, they began to open normally.

I have the exact same issue
 My device Android version is 6
It works when I use `getExternalStorageDirectory` instead of `getApplicationDocumentsDirectory` Or `getTemporaryDirectory`
and cant be used with [https://pub.dev/packages/file_picker](https://pub.dev/packages/file_picker) as it uses the above directory

Also this is **NOT** happening on my second device with android 11
